=== kartverket/backstage-plugin-risk-scorecard-backend/docs/risc_schema_en_v3_3.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://kartverket.github.io/backstage-plugin-risk-scorecard-backend/risc_schema_en_v3_3.json",
  "title": "Risk Scorecard (RiSc)",
  "description": "Schema for risk scorecard",
  "type": "object",
  "properties": {
    "schemaVersion": {
      "description": "Schema version",
      "type": "string",
      "default": "'3.3'"
    },
    "title": {
      "description": "Title of the risk scorecard",
      "type": "string"
    },
    "scope": {
      "description": "The scope of the score card",
      "type": "string"
    },
    "valuations": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "confidentiality": {
            "type": "string",
            "enum": [
              "Public",
              "Internal",
              "Confidential",
              "Strictly confidential"
            ]
          },
          "integrity": {
            "type": "string",
            "enum": [
              "Insignificant",
              "Expected",
              "Dependent",
              "Critical"
            ]
          },
          "availability": {
            "type": "string",
            "enum": [
              "Insignificant",
              "2 days",
              "4 hours",
              "Immediate"
            ]
          }
        },
        "required": [
          "description",
          "confidentiality",
          "integrity",
          "availability"
        ],
        "additionalProperties": false
      },
      "uniqueItems": true
    },
    "scenarios": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "scenario": {
            "$ref": "#/$defs/scenario"
          }
        },
        "required": [
          "title",
          "scenario"
        ],
        "additionalProperties": false
      }
    },
    "sops": {
      "type": "object"
    }
  },
  "required": [
    "schemaVersion",
    "title",
    "scope",
    "scenarios"
  ],
  "additionalProperties": false,
  "$defs": {
    "risk": {
      "type": "object",
      "properties": {
        "summary": {
          "type": "string"
        },
        "probability": {
          "description": "Number of events/day",
          "type": "number",
          "anyOf": [
            {
              "type": "number",
              "enum": [
                0.01,
                0.1,
                1,
                50,
                300
              ]
            },
            {
              "type": "number",
              "minimum": 0
            }
          ]
        },
        "consequence": {
          "description": "Monetary amount per day",
          "anyOf": [
            {
              "type": "number",
              "enum": [
                1000,
                30000,
                1000000,
                30000000,
                1000000000
              ]
            },
            {
              "type": "number",
              "minimum": 0
            }
          ]
        }
      },
      "required": [
        "probability",
        "consequence"
      ],
      "additionalProperties": false
    },
    "url": {
      "type": "string",
      "format": "uri",
      "pattern": "^(?:(https?|s?ftp):\\/\\/)?(?:([\\w-]+)\\.)?([\\w-]+)\\.([\\w]+)\\/?(?:([^?#$]+))?(?:\\?([^#$]+))?(?:#(.*))?$"
    },
    "scenario": {
      "type": "object",
      "properties": {
        "ID": {
          "type": "string",
          "pattern": "^[a-zA-Z0-9]{5,}$"
        },
        "description": {
          "type": "string"
        },
        "url": {
          "$ref": "#/$defs/url"
        },
        "threatActors": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "Script kiddie",
              "Hacktivist",
              "Reckless employee",
              "Insider",
              "Organised crime",
              "Terrorist organisation",
              "Nation/government"
            ]
          }
        },
        "vulnerabilities": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "Compromised admin user",
              "Dependency vulnerability",
              "Disclosed secret",
              "Misconfiguration",
              "Input tampering",
              "User repudiation",
              "Information leak",
              "Denial of service",
              "Escalation of rights"
            ]
          }
        },
        "risk": {
          "$ref": "#/$defs/risk"
        },
        "existingActions": {
          "type": "string"
        },
        "actions": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "title": {
                "type": "string"
              },
              "action": {
                "$ref": "#/$defs/action"
              }
            },
            "required": [
              "title",
              "action"
            ],
            "additionalProperties": false
          }
        },
        "remainingRisk": {
          "$ref": "#/$defs/risk"
        }
      },
      "required": [
        "ID",
        "description",
        "threatActors",
        "vulnerabilities",
        "risk",
        "actions",
        "remainingRisk"
      ],
      "additionalProperties": false
    },
    "action": {
      "type": "object",
      "properties": {
        "ID": {
          "type": "string",
          "pattern": "^[a-zA-Z0-9]{5,}$"
        },
        "description": {
          "type": "string"
        },
        "url": {
          "anyOf": [
            {"$ref": "#/$defs/url"},
            {
              "type": "string",
              "maxLength": 0
            }
          ]
        },
        "owner": {
          "type": "string"
        },
        "deadline": {
          "type": "string",
          "format": "date"
        },
        "status": {
          "type": "string",
          "enum": [
            "Not started",
            "In progress",
            "On hold",
            "Completed",
            "Aborted"
          ]
        }
      },
      "required": [
        "ID",
        "description",
        "status"
      ],
      "additionalProperties": false
    }
  }
}

=== kartverket/backstage-plugin-risk-scorecard-backend/src/test/resources/3.3.json
{
  "schemaVersion": "3.3",
  "title": "Transformasjon",
  "scope": "Sikkerhet av backend.",
  "valuations": [],
  "scenarios": [
    {
      "title": "Ondsinnet bruker ønsker å ta ned løsningen. ",
      "scenario": {
        "ID": "14Kap",
        "description": "Ondsinnet bruer ønsker å ta ned løsningen for å lage kaos hos kartveket.",
        "threatActors": [
          "Organised crime"
        ],
        "vulnerabilities": [
          "User repudiation",
          "Compromised admin user",
          "Escalation of rights",
          "Disclosed secret",
          "Denial of service",
          "Misconfiguration"
        ],
        "risk": {
          "summary": "",
          "probability": 1,
          "consequence": 1000
        },
        "existingActions": "Ddos protection. ",
        "actions": [
          {
            "title": "Innlogging",
            "action": {
              "ID": "w100Q",
              "description": "Innlogging. ",
              "owner": "Kåre",
              "deadline": "2024-06-12",
              "status": "Not started"
            }
          },
          {
            "title": "",
            "action": {
              "ID": "z4B01",
              "description": "Innlogging. ",
              "status": "Not started"
            }
          }
        ],
        "remainingRisk": {
          "summary": "",
          "probability": 0.1,
          "consequence": 1000
        }
      }
    },
    {
      "title": "Tilgang til administratorbruker havner i feil hender.",
      "scenario": {
        "ID": "2dsFd",
        "description": "Tilgang til administratorbruker havner i feil hender og persondata havner på avveie.",
        "threatActors": [
          "Organised crime"
        ],
        "vulnerabilities": [
          "Misconfiguration"
        ],
        "risk": {
          "summary": "",
          "probability": 300,
          "consequence": 1000000000
        },
        "actions": [
          {
            "title": "",
            "action": {
              "ID": "w100Q",
              "description": "Innlogging. ",
              "status": "Not started"
            }
          }
        ],
        "remainingRisk": {
          "summary": "",
          "probability": 0.123,
          "consequence": 198000
        }
      }
    }
  ]
}

=== kartverket/backstage-plugin-risk-scorecard-backend/src/test/resources/3.2.json
{
  "schemaVersion": "3.2",
  "title": "Transformasjon",
  "scope": "Sikkerhet av backend.",
  "valuations": [],
  "scenarios": [
    {
      "title": "Ondsinnet bruker ønsker å ta ned løsningen. ",
      "scenario": {
        "ID": "14Kap",
        "description": "Ondsinnet bruer ønsker å ta ned løsningen for å lage kaos hos kartveket.",
        "threatActors": [
          "Organised crime"
        ],
        "vulnerabilities": [
          "Input tampering",
          "Denial of service"
        ],
        "risk": {
          "summary": "",
          "probability": 1,
          "consequence": 1000
        },
        "existingActions": "Ddos protection. ",
        "actions": [
          {
            "title": "Innlogging",
            "action": {
              "ID": "w100Q",
              "description": "Innlogging. ",
              "owner": "Kåre",
              "deadline": "2024-06-12",
              "status": "Not started"
            }
          }
        ],
        "remainingRisk": {
          "summary": "",
          "probability": 0.1,
          "consequence": 1000
        }
      }
    }
  ]
}
